class PostRequestBody {
  final String text;
  final String authorId;
  final String? imageUrl;
  final String? videoUrl;
  final String? fileUrl;

  final String? imagePublicId;
  final String? videoPublicId;
  final String? filePublicId;

  const PostRequestBody({
    required this.text,
    required this.authorId,
    this.imageUrl,
    this.videoUrl,
    this.fileUrl,
    this.imagePublicId,
    this.videoPublicId,
    this.filePublicId,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'text': text,
      'author_id': authorId,
      'image_url': imageUrl,
      'video_url': videoUrl,
      'file_url': fileUrl,
      'image_public_id': imagePublicId,
      'video_public_id': videoPublicId,
      'file_public_id': filePublicId,
    };
  }

  factory PostRequestBody.fromMap(Map<String, dynamic> map) {
    return PostRequestBody(
      text: map['text'] as String,
      authorId: map['author_id'] as String,
      imageUrl: map['image_url'] as String?,
      videoUrl: map['video_url'] as String?,
      fileUrl: map['file_url'] as String?,

      // not necessary to include public IDs in the request body, as they are usually generated by the server or cloud storage service upon upload. However, if you want to include them, you can uncomment the following lines:

      // imagePublicId: map['image_public_id'] as String?,
      // videoPublicId: map['video_public_id'] as String?,
      // filePublicId: map['file_public_id'] as String?,
    );
  }
}
